### ISSUE TITLE
comment in blog

### ISSUE THREAD

**Issue by srfrnk** [doitintl/gSlack#3]
Looks good, but I’ve had trouble. Firstly `protoPayload.authenticationInfo.principalEmail` was null and crashed the app. I removed it and the function executes successfully but no Slack message is showing up.

**Comment by srfrnk** [comment]
@spark2ignite I need a new project connected to billing to test the complaint

**Comment by spark2ignite** [comment]
@srfrnk here is the project: https://console.cloud.google.com/home/dashboard?project=gslack-playground

**Comment by srfrnk** [comment]
Looks to be working fine.
Just followed the instructions in the [README.md](https://github.com/doitintl/gSlack/blob/master/README.md) on a brand new project and got these:
![gcp doit international slack](https://user-images.githubusercontent.com/1501654/28358798-df6d66f6-6c78-11e7-8c0b-08f1f3d91b29.jpg)
